name: Build
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      - master
jobs:
  bootstrap:
    strategy:
      matrix:
        os:
          - ubuntu-20.04
          - macos-latest
          - windows-latest

    name: run-precommit
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v2.3.3

      - uses: actions/setup-python@v2.1.3
        with:
          python-version: "3.x"

      - name: run pre-commit
        uses: pre-commit/action@v2.0.0
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
